fix AttributeError: 'module' object has no attribute '_get_path'
With buildout 1.4.4 I've been getting the following error. This patch fixes it for me:

An internal error occured due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/dimo/.buildout/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/buildout.py", line 1684, in main
    getattr(buildout, command)(args)
  File "/Users/dimo/.buildout/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/buildout.py", line 525, in install
    installed_files = self[part]._call(update)
  File "/Users/dimo/.buildout/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/buildout.py", line 1227, in _call
    return f()
  File "/Users/dimo/.buildout/eggs/eqb.recipe.uwsgi-0.0.2-py2.7.egg/eqb/recipe/uwsgi/__init__.py", line 186, in update
    self.create_conf_xml()
  File "/Users/dimo/.buildout/eggs/eqb.recipe.uwsgi-0.0.2-py2.7.egg/eqb/recipe/uwsgi/__init__.py", line 150, in create_conf_xml
    paths = zc.buildout.easy_install._get_path(ws, self.get_extra_paths())
AttributeError: 'module' object has no attribute '_get_path'